# -*- coding: utf-8 -*-
"""Batch vs Stochastics vs Mini Batch Gradient Descent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KuxC-z4qfmx60Ib1utLHz4V3Xvto0CGe
"""

import pandas as pd
import numpy as np
import tensorflow as tp
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense
import seaborn as sns

sns.get_dataset_names()

df=sns.load_dataset("diamonds")

df.shape

df.head()

df.info()

df["cut"].value_counts()

df["color"].value_counts()

df["clarity"].value_counts()

from sklearn.preprocessing import LabelEncoder

# la=LabelEncoder()
# df["cut"]=la.fit_transform(df["cut"])
# df["clarity"]=la.fit_transform(df["clarity"])
# df["color"]=la.fit_transform(df["color"])

df.head()

# df=pd.get_dummies(df,columns=["cut","color","clarity"],drop_first=True).astype(int)

df.head()

df.shape

df.info()

df.describe()

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

df.shape

x=df.drop(columns=["price"])
y=df["price"]

x

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

ssl=StandardScaler()

# x_train_scaled=ssl.fit_transform(x_train)
# x_test_scaled=ssl.transform(x_test)

# x_train_scaled

model=Sequential()

model.add(Dense(122,activation="relu",input_dim=9))
model.add(Dense(122,activation="relu"))
model.add(Dense(122,activation="relu"))
model.add(Dense(122,activation="relu"))
model.add(Dense(12,activation="relu"))
model.add(Dense(12,activation="relu"))
model.add(Dense(1,activation="linear"))

model.summary()

model.compile(optimizer="adam",loss="mean_squared_error",metrics=["r2_score"])

history=model.fit(x_train,y_train,batch_size=56,epochs=28,validation_split=0.2)

pred_y=model.predict(x_test)

from sklearn.metrics import r2_score,mean_squared_error

r2_score(y_test,pred_y)

mean_squared_error(y_test,pred_y)

import matplotlib.pyplot as plt

plt.plot(history.history["loss"])
plt.plot(history.history["val_loss"])

plt.plot(history.history["r2_score"])
plt.plot(history.history["val_r2_score"])
plt.legend()

